// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messageList.proto

package com.ry.base.proto.impl;

public interface AppStatusRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ry.base.proto.impl.AppStatusRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 status = 1;</code>
   * @return The status.
   */
  int getStatus();
}
