// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messageList.proto

package com.ry.base.proto.impl;

public interface LoginRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ry.base.proto.impl.LoginRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string phone = 1;</code>
   * @return The phone.
   */
  java.lang.String getPhone();
  /**
   * <code>string phone = 1;</code>
   * @return The bytes for phone.
   */
  com.google.protobuf.ByteString
      getPhoneBytes();

  /**
   * <code>string verifyCode = 2;</code>
   * @return The verifyCode.
   */
  java.lang.String getVerifyCode();
  /**
   * <code>string verifyCode = 2;</code>
   * @return The bytes for verifyCode.
   */
  com.google.protobuf.ByteString
      getVerifyCodeBytes();
}
