// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messageBase.proto

package com.ry.base.proto.impl;

public interface MessageHeaderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ry.base.proto.impl.MessageHeader)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.ry.base.proto.impl.MessageID msgId = 1;</code>
   * @return The enum numeric value on the wire for msgId.
   */
  int getMsgIdValue();
  /**
   * <code>.com.ry.base.proto.impl.MessageID msgId = 1;</code>
   * @return The msgId.
   */
  com.ry.base.proto.impl.MessageID getMsgId();

  /**
   * <code>.com.ry.base.proto.impl.MessageType msgType = 2;</code>
   * @return The enum numeric value on the wire for msgType.
   */
  int getMsgTypeValue();
  /**
   * <code>.com.ry.base.proto.impl.MessageType msgType = 2;</code>
   * @return The msgType.
   */
  com.ry.base.proto.impl.MessageType getMsgType();

  /**
   * <code>string version = 3;</code>
   * @return The version.
   */
  java.lang.String getVersion();
  /**
   * <code>string version = 3;</code>
   * @return The bytes for version.
   */
  com.google.protobuf.ByteString
      getVersionBytes();

  /**
   * <code>string source = 4;</code>
   * @return The source.
   */
  java.lang.String getSource();
  /**
   * <code>string source = 4;</code>
   * @return The bytes for source.
   */
  com.google.protobuf.ByteString
      getSourceBytes();

  /**
   * <code>string token = 5;</code>
   * @return The token.
   */
  java.lang.String getToken();
  /**
   * <code>string token = 5;</code>
   * @return The bytes for token.
   */
  com.google.protobuf.ByteString
      getTokenBytes();
}
