// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messageType.proto

package com.ry.base.proto.impl;

public final class MessageTypeOuterClass {
  private MessageTypeOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021messageType.proto\022\026com.ry.base.proto.i" +
      "mpl*C\n\013MessageType\022\013\n\007Request\020\000\022\014\n\010Respo" +
      "nse\020\001\022\n\n\006Notify\020\002\022\r\n\tBroadcast\020\003B\002P\001b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
