// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messageList.proto

package com.ry.base.proto.impl;

/**
 * Protobuf enum {@code com.ry.base.proto.impl.MessageID}
 */
public enum MessageID
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>LoginReq = 0;</code>
   */
  LoginReq(0),
  /**
   * <code>LoginResp = 1;</code>
   */
  LoginResp(1),
  /**
   * <code>LogoutReq = 2;</code>
   */
  LogoutReq(2),
  /**
   * <code>LogoutResp = 3;</code>
   */
  LogoutResp(3),
  /**
   * <code>HeartBeatReq = 4;</code>
   */
  HeartBeatReq(4),
  /**
   * <code>HeartBeatResp = 5;</code>
   */
  HeartBeatResp(5),
  /**
   * <code>AppStatusReq = 6;</code>
   */
  AppStatusReq(6),
  /**
   * <code>AppStatusResp = 7;</code>
   */
  AppStatusResp(7),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>LoginReq = 0;</code>
   */
  public static final int LoginReq_VALUE = 0;
  /**
   * <code>LoginResp = 1;</code>
   */
  public static final int LoginResp_VALUE = 1;
  /**
   * <code>LogoutReq = 2;</code>
   */
  public static final int LogoutReq_VALUE = 2;
  /**
   * <code>LogoutResp = 3;</code>
   */
  public static final int LogoutResp_VALUE = 3;
  /**
   * <code>HeartBeatReq = 4;</code>
   */
  public static final int HeartBeatReq_VALUE = 4;
  /**
   * <code>HeartBeatResp = 5;</code>
   */
  public static final int HeartBeatResp_VALUE = 5;
  /**
   * <code>AppStatusReq = 6;</code>
   */
  public static final int AppStatusReq_VALUE = 6;
  /**
   * <code>AppStatusResp = 7;</code>
   */
  public static final int AppStatusResp_VALUE = 7;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static MessageID valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static MessageID forNumber(int value) {
    switch (value) {
      case 0: return LoginReq;
      case 1: return LoginResp;
      case 2: return LogoutReq;
      case 3: return LogoutResp;
      case 4: return HeartBeatReq;
      case 5: return HeartBeatResp;
      case 6: return AppStatusReq;
      case 7: return AppStatusResp;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<MessageID>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      MessageID> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<MessageID>() {
          public MessageID findValueByNumber(int number) {
            return MessageID.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.ry.base.proto.impl.MessageList.getDescriptor().getEnumTypes().get(0);
  }

  private static final MessageID[] VALUES = values();

  public static MessageID valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private MessageID(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.ry.base.proto.impl.MessageID)
}

