// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messageBase.proto

package com.ry.base.proto.impl;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ry.base.proto.impl.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.ry.base.proto.impl.MessageHeader msgHeader = 1;</code>
   * @return Whether the msgHeader field is set.
   */
  boolean hasMsgHeader();
  /**
   * <code>.com.ry.base.proto.impl.MessageHeader msgHeader = 1;</code>
   * @return The msgHeader.
   */
  com.ry.base.proto.impl.MessageHeader getMsgHeader();
  /**
   * <code>.com.ry.base.proto.impl.MessageHeader msgHeader = 1;</code>
   */
  com.ry.base.proto.impl.MessageHeaderOrBuilder getMsgHeaderOrBuilder();

  /**
   * <code>.com.ry.base.proto.impl.MessageBody msgBody = 2;</code>
   * @return Whether the msgBody field is set.
   */
  boolean hasMsgBody();
  /**
   * <code>.com.ry.base.proto.impl.MessageBody msgBody = 2;</code>
   * @return The msgBody.
   */
  com.ry.base.proto.impl.MessageBody getMsgBody();
  /**
   * <code>.com.ry.base.proto.impl.MessageBody msgBody = 2;</code>
   */
  com.ry.base.proto.impl.MessageBodyOrBuilder getMsgBodyOrBuilder();
}
