// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messageBase.proto

package com.ry.base.proto.impl;

/**
 * Protobuf type {@code com.ry.base.proto.impl.MessageBody}
 */
public final class MessageBody extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.ry.base.proto.impl.MessageBody)
    MessageBodyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MessageBody.newBuilder() to construct.
  private MessageBody(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MessageBody() {
    resultMsg_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MessageBody();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ry.base.proto.impl.MessageBase.internal_static_com_ry_base_proto_impl_MessageBody_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ry.base.proto.impl.MessageBase.internal_static_com_ry_base_proto_impl_MessageBody_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ry.base.proto.impl.MessageBody.class, com.ry.base.proto.impl.MessageBody.Builder.class);
  }

  private int dataBodyCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object dataBody_;
  public enum DataBodyCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    LOGINREQ(3),
    APPSTATUSREQ(4),
    DATABODY_NOT_SET(0);
    private final int value;
    private DataBodyCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static DataBodyCase valueOf(int value) {
      return forNumber(value);
    }

    public static DataBodyCase forNumber(int value) {
      switch (value) {
        case 3: return LOGINREQ;
        case 4: return APPSTATUSREQ;
        case 0: return DATABODY_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public DataBodyCase
  getDataBodyCase() {
    return DataBodyCase.forNumber(
        dataBodyCase_);
  }

  public static final int RESULTCODE_FIELD_NUMBER = 1;
  private int resultCode_ = 0;
  /**
   * <code>int32 resultCode = 1;</code>
   * @return The resultCode.
   */
  @java.lang.Override
  public int getResultCode() {
    return resultCode_;
  }

  public static final int RESULTMSG_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object resultMsg_ = "";
  /**
   * <code>string resultMsg = 2;</code>
   * @return The resultMsg.
   */
  @java.lang.Override
  public java.lang.String getResultMsg() {
    java.lang.Object ref = resultMsg_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      resultMsg_ = s;
      return s;
    }
  }
  /**
   * <code>string resultMsg = 2;</code>
   * @return The bytes for resultMsg.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getResultMsgBytes() {
    java.lang.Object ref = resultMsg_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      resultMsg_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LOGINREQ_FIELD_NUMBER = 3;
  /**
   * <code>.com.ry.base.proto.impl.LoginRequest loginReq = 3;</code>
   * @return Whether the loginReq field is set.
   */
  @java.lang.Override
  public boolean hasLoginReq() {
    return dataBodyCase_ == 3;
  }
  /**
   * <code>.com.ry.base.proto.impl.LoginRequest loginReq = 3;</code>
   * @return The loginReq.
   */
  @java.lang.Override
  public com.ry.base.proto.impl.LoginRequest getLoginReq() {
    if (dataBodyCase_ == 3) {
       return (com.ry.base.proto.impl.LoginRequest) dataBody_;
    }
    return com.ry.base.proto.impl.LoginRequest.getDefaultInstance();
  }
  /**
   * <code>.com.ry.base.proto.impl.LoginRequest loginReq = 3;</code>
   */
  @java.lang.Override
  public com.ry.base.proto.impl.LoginRequestOrBuilder getLoginReqOrBuilder() {
    if (dataBodyCase_ == 3) {
       return (com.ry.base.proto.impl.LoginRequest) dataBody_;
    }
    return com.ry.base.proto.impl.LoginRequest.getDefaultInstance();
  }

  public static final int APPSTATUSREQ_FIELD_NUMBER = 4;
  /**
   * <code>.com.ry.base.proto.impl.AppStatusRequest appStatusReq = 4;</code>
   * @return Whether the appStatusReq field is set.
   */
  @java.lang.Override
  public boolean hasAppStatusReq() {
    return dataBodyCase_ == 4;
  }
  /**
   * <code>.com.ry.base.proto.impl.AppStatusRequest appStatusReq = 4;</code>
   * @return The appStatusReq.
   */
  @java.lang.Override
  public com.ry.base.proto.impl.AppStatusRequest getAppStatusReq() {
    if (dataBodyCase_ == 4) {
       return (com.ry.base.proto.impl.AppStatusRequest) dataBody_;
    }
    return com.ry.base.proto.impl.AppStatusRequest.getDefaultInstance();
  }
  /**
   * <code>.com.ry.base.proto.impl.AppStatusRequest appStatusReq = 4;</code>
   */
  @java.lang.Override
  public com.ry.base.proto.impl.AppStatusRequestOrBuilder getAppStatusReqOrBuilder() {
    if (dataBodyCase_ == 4) {
       return (com.ry.base.proto.impl.AppStatusRequest) dataBody_;
    }
    return com.ry.base.proto.impl.AppStatusRequest.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (resultCode_ != 0) {
      output.writeInt32(1, resultCode_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(resultMsg_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, resultMsg_);
    }
    if (dataBodyCase_ == 3) {
      output.writeMessage(3, (com.ry.base.proto.impl.LoginRequest) dataBody_);
    }
    if (dataBodyCase_ == 4) {
      output.writeMessage(4, (com.ry.base.proto.impl.AppStatusRequest) dataBody_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (resultCode_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, resultCode_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(resultMsg_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, resultMsg_);
    }
    if (dataBodyCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (com.ry.base.proto.impl.LoginRequest) dataBody_);
    }
    if (dataBodyCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (com.ry.base.proto.impl.AppStatusRequest) dataBody_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ry.base.proto.impl.MessageBody)) {
      return super.equals(obj);
    }
    com.ry.base.proto.impl.MessageBody other = (com.ry.base.proto.impl.MessageBody) obj;

    if (getResultCode()
        != other.getResultCode()) return false;
    if (!getResultMsg()
        .equals(other.getResultMsg())) return false;
    if (!getDataBodyCase().equals(other.getDataBodyCase())) return false;
    switch (dataBodyCase_) {
      case 3:
        if (!getLoginReq()
            .equals(other.getLoginReq())) return false;
        break;
      case 4:
        if (!getAppStatusReq()
            .equals(other.getAppStatusReq())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RESULTCODE_FIELD_NUMBER;
    hash = (53 * hash) + getResultCode();
    hash = (37 * hash) + RESULTMSG_FIELD_NUMBER;
    hash = (53 * hash) + getResultMsg().hashCode();
    switch (dataBodyCase_) {
      case 3:
        hash = (37 * hash) + LOGINREQ_FIELD_NUMBER;
        hash = (53 * hash) + getLoginReq().hashCode();
        break;
      case 4:
        hash = (37 * hash) + APPSTATUSREQ_FIELD_NUMBER;
        hash = (53 * hash) + getAppStatusReq().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ry.base.proto.impl.MessageBody parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ry.base.proto.impl.MessageBody parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ry.base.proto.impl.MessageBody parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ry.base.proto.impl.MessageBody parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ry.base.proto.impl.MessageBody parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ry.base.proto.impl.MessageBody parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ry.base.proto.impl.MessageBody parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ry.base.proto.impl.MessageBody parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.ry.base.proto.impl.MessageBody parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.ry.base.proto.impl.MessageBody parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ry.base.proto.impl.MessageBody parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ry.base.proto.impl.MessageBody parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ry.base.proto.impl.MessageBody prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.ry.base.proto.impl.MessageBody}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.ry.base.proto.impl.MessageBody)
      com.ry.base.proto.impl.MessageBodyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ry.base.proto.impl.MessageBase.internal_static_com_ry_base_proto_impl_MessageBody_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ry.base.proto.impl.MessageBase.internal_static_com_ry_base_proto_impl_MessageBody_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ry.base.proto.impl.MessageBody.class, com.ry.base.proto.impl.MessageBody.Builder.class);
    }

    // Construct using com.ry.base.proto.impl.MessageBody.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      resultCode_ = 0;
      resultMsg_ = "";
      if (loginReqBuilder_ != null) {
        loginReqBuilder_.clear();
      }
      if (appStatusReqBuilder_ != null) {
        appStatusReqBuilder_.clear();
      }
      dataBodyCase_ = 0;
      dataBody_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ry.base.proto.impl.MessageBase.internal_static_com_ry_base_proto_impl_MessageBody_descriptor;
    }

    @java.lang.Override
    public com.ry.base.proto.impl.MessageBody getDefaultInstanceForType() {
      return com.ry.base.proto.impl.MessageBody.getDefaultInstance();
    }

    @java.lang.Override
    public com.ry.base.proto.impl.MessageBody build() {
      com.ry.base.proto.impl.MessageBody result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ry.base.proto.impl.MessageBody buildPartial() {
      com.ry.base.proto.impl.MessageBody result = new com.ry.base.proto.impl.MessageBody(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(com.ry.base.proto.impl.MessageBody result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.resultCode_ = resultCode_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.resultMsg_ = resultMsg_;
      }
    }

    private void buildPartialOneofs(com.ry.base.proto.impl.MessageBody result) {
      result.dataBodyCase_ = dataBodyCase_;
      result.dataBody_ = this.dataBody_;
      if (dataBodyCase_ == 3 &&
          loginReqBuilder_ != null) {
        result.dataBody_ = loginReqBuilder_.build();
      }
      if (dataBodyCase_ == 4 &&
          appStatusReqBuilder_ != null) {
        result.dataBody_ = appStatusReqBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ry.base.proto.impl.MessageBody) {
        return mergeFrom((com.ry.base.proto.impl.MessageBody)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ry.base.proto.impl.MessageBody other) {
      if (other == com.ry.base.proto.impl.MessageBody.getDefaultInstance()) return this;
      if (other.getResultCode() != 0) {
        setResultCode(other.getResultCode());
      }
      if (!other.getResultMsg().isEmpty()) {
        resultMsg_ = other.resultMsg_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      switch (other.getDataBodyCase()) {
        case LOGINREQ: {
          mergeLoginReq(other.getLoginReq());
          break;
        }
        case APPSTATUSREQ: {
          mergeAppStatusReq(other.getAppStatusReq());
          break;
        }
        case DATABODY_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              resultCode_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              resultMsg_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getLoginReqFieldBuilder().getBuilder(),
                  extensionRegistry);
              dataBodyCase_ = 3;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getAppStatusReqFieldBuilder().getBuilder(),
                  extensionRegistry);
              dataBodyCase_ = 4;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int dataBodyCase_ = 0;
    private java.lang.Object dataBody_;
    public DataBodyCase
        getDataBodyCase() {
      return DataBodyCase.forNumber(
          dataBodyCase_);
    }

    public Builder clearDataBody() {
      dataBodyCase_ = 0;
      dataBody_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private int resultCode_ ;
    /**
     * <code>int32 resultCode = 1;</code>
     * @return The resultCode.
     */
    @java.lang.Override
    public int getResultCode() {
      return resultCode_;
    }
    /**
     * <code>int32 resultCode = 1;</code>
     * @param value The resultCode to set.
     * @return This builder for chaining.
     */
    public Builder setResultCode(int value) {

      resultCode_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 resultCode = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearResultCode() {
      bitField0_ = (bitField0_ & ~0x00000001);
      resultCode_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object resultMsg_ = "";
    /**
     * <code>string resultMsg = 2;</code>
     * @return The resultMsg.
     */
    public java.lang.String getResultMsg() {
      java.lang.Object ref = resultMsg_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resultMsg_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string resultMsg = 2;</code>
     * @return The bytes for resultMsg.
     */
    public com.google.protobuf.ByteString
        getResultMsgBytes() {
      java.lang.Object ref = resultMsg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resultMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string resultMsg = 2;</code>
     * @param value The resultMsg to set.
     * @return This builder for chaining.
     */
    public Builder setResultMsg(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      resultMsg_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string resultMsg = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearResultMsg() {
      resultMsg_ = getDefaultInstance().getResultMsg();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string resultMsg = 2;</code>
     * @param value The bytes for resultMsg to set.
     * @return This builder for chaining.
     */
    public Builder setResultMsgBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      resultMsg_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.ry.base.proto.impl.LoginRequest, com.ry.base.proto.impl.LoginRequest.Builder, com.ry.base.proto.impl.LoginRequestOrBuilder> loginReqBuilder_;
    /**
     * <code>.com.ry.base.proto.impl.LoginRequest loginReq = 3;</code>
     * @return Whether the loginReq field is set.
     */
    @java.lang.Override
    public boolean hasLoginReq() {
      return dataBodyCase_ == 3;
    }
    /**
     * <code>.com.ry.base.proto.impl.LoginRequest loginReq = 3;</code>
     * @return The loginReq.
     */
    @java.lang.Override
    public com.ry.base.proto.impl.LoginRequest getLoginReq() {
      if (loginReqBuilder_ == null) {
        if (dataBodyCase_ == 3) {
          return (com.ry.base.proto.impl.LoginRequest) dataBody_;
        }
        return com.ry.base.proto.impl.LoginRequest.getDefaultInstance();
      } else {
        if (dataBodyCase_ == 3) {
          return loginReqBuilder_.getMessage();
        }
        return com.ry.base.proto.impl.LoginRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.com.ry.base.proto.impl.LoginRequest loginReq = 3;</code>
     */
    public Builder setLoginReq(com.ry.base.proto.impl.LoginRequest value) {
      if (loginReqBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dataBody_ = value;
        onChanged();
      } else {
        loginReqBuilder_.setMessage(value);
      }
      dataBodyCase_ = 3;
      return this;
    }
    /**
     * <code>.com.ry.base.proto.impl.LoginRequest loginReq = 3;</code>
     */
    public Builder setLoginReq(
        com.ry.base.proto.impl.LoginRequest.Builder builderForValue) {
      if (loginReqBuilder_ == null) {
        dataBody_ = builderForValue.build();
        onChanged();
      } else {
        loginReqBuilder_.setMessage(builderForValue.build());
      }
      dataBodyCase_ = 3;
      return this;
    }
    /**
     * <code>.com.ry.base.proto.impl.LoginRequest loginReq = 3;</code>
     */
    public Builder mergeLoginReq(com.ry.base.proto.impl.LoginRequest value) {
      if (loginReqBuilder_ == null) {
        if (dataBodyCase_ == 3 &&
            dataBody_ != com.ry.base.proto.impl.LoginRequest.getDefaultInstance()) {
          dataBody_ = com.ry.base.proto.impl.LoginRequest.newBuilder((com.ry.base.proto.impl.LoginRequest) dataBody_)
              .mergeFrom(value).buildPartial();
        } else {
          dataBody_ = value;
        }
        onChanged();
      } else {
        if (dataBodyCase_ == 3) {
          loginReqBuilder_.mergeFrom(value);
        } else {
          loginReqBuilder_.setMessage(value);
        }
      }
      dataBodyCase_ = 3;
      return this;
    }
    /**
     * <code>.com.ry.base.proto.impl.LoginRequest loginReq = 3;</code>
     */
    public Builder clearLoginReq() {
      if (loginReqBuilder_ == null) {
        if (dataBodyCase_ == 3) {
          dataBodyCase_ = 0;
          dataBody_ = null;
          onChanged();
        }
      } else {
        if (dataBodyCase_ == 3) {
          dataBodyCase_ = 0;
          dataBody_ = null;
        }
        loginReqBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.com.ry.base.proto.impl.LoginRequest loginReq = 3;</code>
     */
    public com.ry.base.proto.impl.LoginRequest.Builder getLoginReqBuilder() {
      return getLoginReqFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.ry.base.proto.impl.LoginRequest loginReq = 3;</code>
     */
    @java.lang.Override
    public com.ry.base.proto.impl.LoginRequestOrBuilder getLoginReqOrBuilder() {
      if ((dataBodyCase_ == 3) && (loginReqBuilder_ != null)) {
        return loginReqBuilder_.getMessageOrBuilder();
      } else {
        if (dataBodyCase_ == 3) {
          return (com.ry.base.proto.impl.LoginRequest) dataBody_;
        }
        return com.ry.base.proto.impl.LoginRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.com.ry.base.proto.impl.LoginRequest loginReq = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ry.base.proto.impl.LoginRequest, com.ry.base.proto.impl.LoginRequest.Builder, com.ry.base.proto.impl.LoginRequestOrBuilder> 
        getLoginReqFieldBuilder() {
      if (loginReqBuilder_ == null) {
        if (!(dataBodyCase_ == 3)) {
          dataBody_ = com.ry.base.proto.impl.LoginRequest.getDefaultInstance();
        }
        loginReqBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.ry.base.proto.impl.LoginRequest, com.ry.base.proto.impl.LoginRequest.Builder, com.ry.base.proto.impl.LoginRequestOrBuilder>(
                (com.ry.base.proto.impl.LoginRequest) dataBody_,
                getParentForChildren(),
                isClean());
        dataBody_ = null;
      }
      dataBodyCase_ = 3;
      onChanged();
      return loginReqBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.ry.base.proto.impl.AppStatusRequest, com.ry.base.proto.impl.AppStatusRequest.Builder, com.ry.base.proto.impl.AppStatusRequestOrBuilder> appStatusReqBuilder_;
    /**
     * <code>.com.ry.base.proto.impl.AppStatusRequest appStatusReq = 4;</code>
     * @return Whether the appStatusReq field is set.
     */
    @java.lang.Override
    public boolean hasAppStatusReq() {
      return dataBodyCase_ == 4;
    }
    /**
     * <code>.com.ry.base.proto.impl.AppStatusRequest appStatusReq = 4;</code>
     * @return The appStatusReq.
     */
    @java.lang.Override
    public com.ry.base.proto.impl.AppStatusRequest getAppStatusReq() {
      if (appStatusReqBuilder_ == null) {
        if (dataBodyCase_ == 4) {
          return (com.ry.base.proto.impl.AppStatusRequest) dataBody_;
        }
        return com.ry.base.proto.impl.AppStatusRequest.getDefaultInstance();
      } else {
        if (dataBodyCase_ == 4) {
          return appStatusReqBuilder_.getMessage();
        }
        return com.ry.base.proto.impl.AppStatusRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.com.ry.base.proto.impl.AppStatusRequest appStatusReq = 4;</code>
     */
    public Builder setAppStatusReq(com.ry.base.proto.impl.AppStatusRequest value) {
      if (appStatusReqBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dataBody_ = value;
        onChanged();
      } else {
        appStatusReqBuilder_.setMessage(value);
      }
      dataBodyCase_ = 4;
      return this;
    }
    /**
     * <code>.com.ry.base.proto.impl.AppStatusRequest appStatusReq = 4;</code>
     */
    public Builder setAppStatusReq(
        com.ry.base.proto.impl.AppStatusRequest.Builder builderForValue) {
      if (appStatusReqBuilder_ == null) {
        dataBody_ = builderForValue.build();
        onChanged();
      } else {
        appStatusReqBuilder_.setMessage(builderForValue.build());
      }
      dataBodyCase_ = 4;
      return this;
    }
    /**
     * <code>.com.ry.base.proto.impl.AppStatusRequest appStatusReq = 4;</code>
     */
    public Builder mergeAppStatusReq(com.ry.base.proto.impl.AppStatusRequest value) {
      if (appStatusReqBuilder_ == null) {
        if (dataBodyCase_ == 4 &&
            dataBody_ != com.ry.base.proto.impl.AppStatusRequest.getDefaultInstance()) {
          dataBody_ = com.ry.base.proto.impl.AppStatusRequest.newBuilder((com.ry.base.proto.impl.AppStatusRequest) dataBody_)
              .mergeFrom(value).buildPartial();
        } else {
          dataBody_ = value;
        }
        onChanged();
      } else {
        if (dataBodyCase_ == 4) {
          appStatusReqBuilder_.mergeFrom(value);
        } else {
          appStatusReqBuilder_.setMessage(value);
        }
      }
      dataBodyCase_ = 4;
      return this;
    }
    /**
     * <code>.com.ry.base.proto.impl.AppStatusRequest appStatusReq = 4;</code>
     */
    public Builder clearAppStatusReq() {
      if (appStatusReqBuilder_ == null) {
        if (dataBodyCase_ == 4) {
          dataBodyCase_ = 0;
          dataBody_ = null;
          onChanged();
        }
      } else {
        if (dataBodyCase_ == 4) {
          dataBodyCase_ = 0;
          dataBody_ = null;
        }
        appStatusReqBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.com.ry.base.proto.impl.AppStatusRequest appStatusReq = 4;</code>
     */
    public com.ry.base.proto.impl.AppStatusRequest.Builder getAppStatusReqBuilder() {
      return getAppStatusReqFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.ry.base.proto.impl.AppStatusRequest appStatusReq = 4;</code>
     */
    @java.lang.Override
    public com.ry.base.proto.impl.AppStatusRequestOrBuilder getAppStatusReqOrBuilder() {
      if ((dataBodyCase_ == 4) && (appStatusReqBuilder_ != null)) {
        return appStatusReqBuilder_.getMessageOrBuilder();
      } else {
        if (dataBodyCase_ == 4) {
          return (com.ry.base.proto.impl.AppStatusRequest) dataBody_;
        }
        return com.ry.base.proto.impl.AppStatusRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.com.ry.base.proto.impl.AppStatusRequest appStatusReq = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ry.base.proto.impl.AppStatusRequest, com.ry.base.proto.impl.AppStatusRequest.Builder, com.ry.base.proto.impl.AppStatusRequestOrBuilder> 
        getAppStatusReqFieldBuilder() {
      if (appStatusReqBuilder_ == null) {
        if (!(dataBodyCase_ == 4)) {
          dataBody_ = com.ry.base.proto.impl.AppStatusRequest.getDefaultInstance();
        }
        appStatusReqBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.ry.base.proto.impl.AppStatusRequest, com.ry.base.proto.impl.AppStatusRequest.Builder, com.ry.base.proto.impl.AppStatusRequestOrBuilder>(
                (com.ry.base.proto.impl.AppStatusRequest) dataBody_,
                getParentForChildren(),
                isClean());
        dataBody_ = null;
      }
      dataBodyCase_ = 4;
      onChanged();
      return appStatusReqBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.ry.base.proto.impl.MessageBody)
  }

  // @@protoc_insertion_point(class_scope:com.ry.base.proto.impl.MessageBody)
  private static final com.ry.base.proto.impl.MessageBody DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ry.base.proto.impl.MessageBody();
  }

  public static com.ry.base.proto.impl.MessageBody getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MessageBody>
      PARSER = new com.google.protobuf.AbstractParser<MessageBody>() {
    @java.lang.Override
    public MessageBody parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<MessageBody> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MessageBody> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ry.base.proto.impl.MessageBody getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

