// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messageBase.proto

package com.ry.base.proto.impl;

public interface MessageBodyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ry.base.proto.impl.MessageBody)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 resultCode = 1;</code>
   * @return The resultCode.
   */
  int getResultCode();

  /**
   * <code>string resultMsg = 2;</code>
   * @return The resultMsg.
   */
  java.lang.String getResultMsg();
  /**
   * <code>string resultMsg = 2;</code>
   * @return The bytes for resultMsg.
   */
  com.google.protobuf.ByteString
      getResultMsgBytes();

  /**
   * <code>.com.ry.base.proto.impl.LoginRequest loginReq = 3;</code>
   * @return Whether the loginReq field is set.
   */
  boolean hasLoginReq();
  /**
   * <code>.com.ry.base.proto.impl.LoginRequest loginReq = 3;</code>
   * @return The loginReq.
   */
  com.ry.base.proto.impl.LoginRequest getLoginReq();
  /**
   * <code>.com.ry.base.proto.impl.LoginRequest loginReq = 3;</code>
   */
  com.ry.base.proto.impl.LoginRequestOrBuilder getLoginReqOrBuilder();

  /**
   * <code>.com.ry.base.proto.impl.AppStatusRequest appStatusReq = 4;</code>
   * @return Whether the appStatusReq field is set.
   */
  boolean hasAppStatusReq();
  /**
   * <code>.com.ry.base.proto.impl.AppStatusRequest appStatusReq = 4;</code>
   * @return The appStatusReq.
   */
  com.ry.base.proto.impl.AppStatusRequest getAppStatusReq();
  /**
   * <code>.com.ry.base.proto.impl.AppStatusRequest appStatusReq = 4;</code>
   */
  com.ry.base.proto.impl.AppStatusRequestOrBuilder getAppStatusReqOrBuilder();

  com.ry.base.proto.impl.MessageBody.DataBodyCase getDataBodyCase();
}
