// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messageList.proto

package com.ry.base.proto.impl;

public final class MessageList {
  private MessageList() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ry_base_proto_impl_LoginRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ry_base_proto_impl_LoginRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ry_base_proto_impl_AppStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ry_base_proto_impl_AppStatusRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021messageList.proto\022\026com.ry.base.proto.i" +
      "mpl\"1\n\014LoginRequest\022\r\n\005phone\030\001 \001(\t\022\022\n\nve" +
      "rifyCode\030\002 \001(\t\"\"\n\020AppStatusRequest\022\016\n\006st" +
      "atus\030\001 \001(\005*\221\001\n\tMessageID\022\014\n\010LoginReq\020\000\022\r" +
      "\n\tLoginResp\020\001\022\r\n\tLogoutReq\020\002\022\016\n\nLogoutRe" +
      "sp\020\003\022\020\n\014HeartBeatReq\020\004\022\021\n\rHeartBeatResp\020" +
      "\005\022\020\n\014AppStatusReq\020\006\022\021\n\rAppStatusResp\020\007B\002" +
      "P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_ry_base_proto_impl_LoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ry_base_proto_impl_LoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ry_base_proto_impl_LoginRequest_descriptor,
        new java.lang.String[] { "Phone", "VerifyCode", });
    internal_static_com_ry_base_proto_impl_AppStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_ry_base_proto_impl_AppStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ry_base_proto_impl_AppStatusRequest_descriptor,
        new java.lang.String[] { "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
