// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messageBase.proto

package com.ry.base.proto.impl;

/**
 * Protobuf type {@code com.ry.base.proto.impl.Message}
 */
public final class Message extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.ry.base.proto.impl.Message)
    MessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Message.newBuilder() to construct.
  private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Message() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Message();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ry.base.proto.impl.MessageBase.internal_static_com_ry_base_proto_impl_Message_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ry.base.proto.impl.MessageBase.internal_static_com_ry_base_proto_impl_Message_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ry.base.proto.impl.Message.class, com.ry.base.proto.impl.Message.Builder.class);
  }

  public static final int MSGHEADER_FIELD_NUMBER = 1;
  private com.ry.base.proto.impl.MessageHeader msgHeader_;
  /**
   * <code>.com.ry.base.proto.impl.MessageHeader msgHeader = 1;</code>
   * @return Whether the msgHeader field is set.
   */
  @java.lang.Override
  public boolean hasMsgHeader() {
    return msgHeader_ != null;
  }
  /**
   * <code>.com.ry.base.proto.impl.MessageHeader msgHeader = 1;</code>
   * @return The msgHeader.
   */
  @java.lang.Override
  public com.ry.base.proto.impl.MessageHeader getMsgHeader() {
    return msgHeader_ == null ? com.ry.base.proto.impl.MessageHeader.getDefaultInstance() : msgHeader_;
  }
  /**
   * <code>.com.ry.base.proto.impl.MessageHeader msgHeader = 1;</code>
   */
  @java.lang.Override
  public com.ry.base.proto.impl.MessageHeaderOrBuilder getMsgHeaderOrBuilder() {
    return msgHeader_ == null ? com.ry.base.proto.impl.MessageHeader.getDefaultInstance() : msgHeader_;
  }

  public static final int MSGBODY_FIELD_NUMBER = 2;
  private com.ry.base.proto.impl.MessageBody msgBody_;
  /**
   * <code>.com.ry.base.proto.impl.MessageBody msgBody = 2;</code>
   * @return Whether the msgBody field is set.
   */
  @java.lang.Override
  public boolean hasMsgBody() {
    return msgBody_ != null;
  }
  /**
   * <code>.com.ry.base.proto.impl.MessageBody msgBody = 2;</code>
   * @return The msgBody.
   */
  @java.lang.Override
  public com.ry.base.proto.impl.MessageBody getMsgBody() {
    return msgBody_ == null ? com.ry.base.proto.impl.MessageBody.getDefaultInstance() : msgBody_;
  }
  /**
   * <code>.com.ry.base.proto.impl.MessageBody msgBody = 2;</code>
   */
  @java.lang.Override
  public com.ry.base.proto.impl.MessageBodyOrBuilder getMsgBodyOrBuilder() {
    return msgBody_ == null ? com.ry.base.proto.impl.MessageBody.getDefaultInstance() : msgBody_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (msgHeader_ != null) {
      output.writeMessage(1, getMsgHeader());
    }
    if (msgBody_ != null) {
      output.writeMessage(2, getMsgBody());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (msgHeader_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getMsgHeader());
    }
    if (msgBody_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getMsgBody());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ry.base.proto.impl.Message)) {
      return super.equals(obj);
    }
    com.ry.base.proto.impl.Message other = (com.ry.base.proto.impl.Message) obj;

    if (hasMsgHeader() != other.hasMsgHeader()) return false;
    if (hasMsgHeader()) {
      if (!getMsgHeader()
          .equals(other.getMsgHeader())) return false;
    }
    if (hasMsgBody() != other.hasMsgBody()) return false;
    if (hasMsgBody()) {
      if (!getMsgBody()
          .equals(other.getMsgBody())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasMsgHeader()) {
      hash = (37 * hash) + MSGHEADER_FIELD_NUMBER;
      hash = (53 * hash) + getMsgHeader().hashCode();
    }
    if (hasMsgBody()) {
      hash = (37 * hash) + MSGBODY_FIELD_NUMBER;
      hash = (53 * hash) + getMsgBody().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ry.base.proto.impl.Message parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ry.base.proto.impl.Message parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ry.base.proto.impl.Message parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ry.base.proto.impl.Message parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ry.base.proto.impl.Message parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ry.base.proto.impl.Message parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ry.base.proto.impl.Message parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ry.base.proto.impl.Message parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.ry.base.proto.impl.Message parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.ry.base.proto.impl.Message parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ry.base.proto.impl.Message parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ry.base.proto.impl.Message parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ry.base.proto.impl.Message prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.ry.base.proto.impl.Message}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.ry.base.proto.impl.Message)
      com.ry.base.proto.impl.MessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ry.base.proto.impl.MessageBase.internal_static_com_ry_base_proto_impl_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ry.base.proto.impl.MessageBase.internal_static_com_ry_base_proto_impl_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ry.base.proto.impl.Message.class, com.ry.base.proto.impl.Message.Builder.class);
    }

    // Construct using com.ry.base.proto.impl.Message.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      msgHeader_ = null;
      if (msgHeaderBuilder_ != null) {
        msgHeaderBuilder_.dispose();
        msgHeaderBuilder_ = null;
      }
      msgBody_ = null;
      if (msgBodyBuilder_ != null) {
        msgBodyBuilder_.dispose();
        msgBodyBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ry.base.proto.impl.MessageBase.internal_static_com_ry_base_proto_impl_Message_descriptor;
    }

    @java.lang.Override
    public com.ry.base.proto.impl.Message getDefaultInstanceForType() {
      return com.ry.base.proto.impl.Message.getDefaultInstance();
    }

    @java.lang.Override
    public com.ry.base.proto.impl.Message build() {
      com.ry.base.proto.impl.Message result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ry.base.proto.impl.Message buildPartial() {
      com.ry.base.proto.impl.Message result = new com.ry.base.proto.impl.Message(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.ry.base.proto.impl.Message result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.msgHeader_ = msgHeaderBuilder_ == null
            ? msgHeader_
            : msgHeaderBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.msgBody_ = msgBodyBuilder_ == null
            ? msgBody_
            : msgBodyBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ry.base.proto.impl.Message) {
        return mergeFrom((com.ry.base.proto.impl.Message)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ry.base.proto.impl.Message other) {
      if (other == com.ry.base.proto.impl.Message.getDefaultInstance()) return this;
      if (other.hasMsgHeader()) {
        mergeMsgHeader(other.getMsgHeader());
      }
      if (other.hasMsgBody()) {
        mergeMsgBody(other.getMsgBody());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getMsgHeaderFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getMsgBodyFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.ry.base.proto.impl.MessageHeader msgHeader_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ry.base.proto.impl.MessageHeader, com.ry.base.proto.impl.MessageHeader.Builder, com.ry.base.proto.impl.MessageHeaderOrBuilder> msgHeaderBuilder_;
    /**
     * <code>.com.ry.base.proto.impl.MessageHeader msgHeader = 1;</code>
     * @return Whether the msgHeader field is set.
     */
    public boolean hasMsgHeader() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.com.ry.base.proto.impl.MessageHeader msgHeader = 1;</code>
     * @return The msgHeader.
     */
    public com.ry.base.proto.impl.MessageHeader getMsgHeader() {
      if (msgHeaderBuilder_ == null) {
        return msgHeader_ == null ? com.ry.base.proto.impl.MessageHeader.getDefaultInstance() : msgHeader_;
      } else {
        return msgHeaderBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.ry.base.proto.impl.MessageHeader msgHeader = 1;</code>
     */
    public Builder setMsgHeader(com.ry.base.proto.impl.MessageHeader value) {
      if (msgHeaderBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msgHeader_ = value;
      } else {
        msgHeaderBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.com.ry.base.proto.impl.MessageHeader msgHeader = 1;</code>
     */
    public Builder setMsgHeader(
        com.ry.base.proto.impl.MessageHeader.Builder builderForValue) {
      if (msgHeaderBuilder_ == null) {
        msgHeader_ = builderForValue.build();
      } else {
        msgHeaderBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.com.ry.base.proto.impl.MessageHeader msgHeader = 1;</code>
     */
    public Builder mergeMsgHeader(com.ry.base.proto.impl.MessageHeader value) {
      if (msgHeaderBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          msgHeader_ != null &&
          msgHeader_ != com.ry.base.proto.impl.MessageHeader.getDefaultInstance()) {
          getMsgHeaderBuilder().mergeFrom(value);
        } else {
          msgHeader_ = value;
        }
      } else {
        msgHeaderBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.com.ry.base.proto.impl.MessageHeader msgHeader = 1;</code>
     */
    public Builder clearMsgHeader() {
      bitField0_ = (bitField0_ & ~0x00000001);
      msgHeader_ = null;
      if (msgHeaderBuilder_ != null) {
        msgHeaderBuilder_.dispose();
        msgHeaderBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.com.ry.base.proto.impl.MessageHeader msgHeader = 1;</code>
     */
    public com.ry.base.proto.impl.MessageHeader.Builder getMsgHeaderBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getMsgHeaderFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.ry.base.proto.impl.MessageHeader msgHeader = 1;</code>
     */
    public com.ry.base.proto.impl.MessageHeaderOrBuilder getMsgHeaderOrBuilder() {
      if (msgHeaderBuilder_ != null) {
        return msgHeaderBuilder_.getMessageOrBuilder();
      } else {
        return msgHeader_ == null ?
            com.ry.base.proto.impl.MessageHeader.getDefaultInstance() : msgHeader_;
      }
    }
    /**
     * <code>.com.ry.base.proto.impl.MessageHeader msgHeader = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ry.base.proto.impl.MessageHeader, com.ry.base.proto.impl.MessageHeader.Builder, com.ry.base.proto.impl.MessageHeaderOrBuilder> 
        getMsgHeaderFieldBuilder() {
      if (msgHeaderBuilder_ == null) {
        msgHeaderBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.ry.base.proto.impl.MessageHeader, com.ry.base.proto.impl.MessageHeader.Builder, com.ry.base.proto.impl.MessageHeaderOrBuilder>(
                getMsgHeader(),
                getParentForChildren(),
                isClean());
        msgHeader_ = null;
      }
      return msgHeaderBuilder_;
    }

    private com.ry.base.proto.impl.MessageBody msgBody_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ry.base.proto.impl.MessageBody, com.ry.base.proto.impl.MessageBody.Builder, com.ry.base.proto.impl.MessageBodyOrBuilder> msgBodyBuilder_;
    /**
     * <code>.com.ry.base.proto.impl.MessageBody msgBody = 2;</code>
     * @return Whether the msgBody field is set.
     */
    public boolean hasMsgBody() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.com.ry.base.proto.impl.MessageBody msgBody = 2;</code>
     * @return The msgBody.
     */
    public com.ry.base.proto.impl.MessageBody getMsgBody() {
      if (msgBodyBuilder_ == null) {
        return msgBody_ == null ? com.ry.base.proto.impl.MessageBody.getDefaultInstance() : msgBody_;
      } else {
        return msgBodyBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.ry.base.proto.impl.MessageBody msgBody = 2;</code>
     */
    public Builder setMsgBody(com.ry.base.proto.impl.MessageBody value) {
      if (msgBodyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msgBody_ = value;
      } else {
        msgBodyBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.com.ry.base.proto.impl.MessageBody msgBody = 2;</code>
     */
    public Builder setMsgBody(
        com.ry.base.proto.impl.MessageBody.Builder builderForValue) {
      if (msgBodyBuilder_ == null) {
        msgBody_ = builderForValue.build();
      } else {
        msgBodyBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.com.ry.base.proto.impl.MessageBody msgBody = 2;</code>
     */
    public Builder mergeMsgBody(com.ry.base.proto.impl.MessageBody value) {
      if (msgBodyBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          msgBody_ != null &&
          msgBody_ != com.ry.base.proto.impl.MessageBody.getDefaultInstance()) {
          getMsgBodyBuilder().mergeFrom(value);
        } else {
          msgBody_ = value;
        }
      } else {
        msgBodyBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.com.ry.base.proto.impl.MessageBody msgBody = 2;</code>
     */
    public Builder clearMsgBody() {
      bitField0_ = (bitField0_ & ~0x00000002);
      msgBody_ = null;
      if (msgBodyBuilder_ != null) {
        msgBodyBuilder_.dispose();
        msgBodyBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.com.ry.base.proto.impl.MessageBody msgBody = 2;</code>
     */
    public com.ry.base.proto.impl.MessageBody.Builder getMsgBodyBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getMsgBodyFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.ry.base.proto.impl.MessageBody msgBody = 2;</code>
     */
    public com.ry.base.proto.impl.MessageBodyOrBuilder getMsgBodyOrBuilder() {
      if (msgBodyBuilder_ != null) {
        return msgBodyBuilder_.getMessageOrBuilder();
      } else {
        return msgBody_ == null ?
            com.ry.base.proto.impl.MessageBody.getDefaultInstance() : msgBody_;
      }
    }
    /**
     * <code>.com.ry.base.proto.impl.MessageBody msgBody = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ry.base.proto.impl.MessageBody, com.ry.base.proto.impl.MessageBody.Builder, com.ry.base.proto.impl.MessageBodyOrBuilder> 
        getMsgBodyFieldBuilder() {
      if (msgBodyBuilder_ == null) {
        msgBodyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.ry.base.proto.impl.MessageBody, com.ry.base.proto.impl.MessageBody.Builder, com.ry.base.proto.impl.MessageBodyOrBuilder>(
                getMsgBody(),
                getParentForChildren(),
                isClean());
        msgBody_ = null;
      }
      return msgBodyBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.ry.base.proto.impl.Message)
  }

  // @@protoc_insertion_point(class_scope:com.ry.base.proto.impl.Message)
  private static final com.ry.base.proto.impl.Message DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ry.base.proto.impl.Message();
  }

  public static com.ry.base.proto.impl.Message getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Message>
      PARSER = new com.google.protobuf.AbstractParser<Message>() {
    @java.lang.Override
    public Message parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Message> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Message> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ry.base.proto.impl.Message getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

